# action.yml
name: 'Alpine Build APK'
author: 'Kalle M. Aagaard <alpine@k-moeller.dk>'
description: 'Build alpine apk'
inputs:
  abuild_key:
    description: 'RSA Key to sign the package'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'  
  color: 'blue'